### ISSUE TITLE
MDTools support for ArcGIS Pro 3.0

### ISSUE THREAD

**Issue by Shane98c** [Esri/mdcs-py#104]
Curious what the outlook for being able to install MDTools on Arc Pro 3 is. 

Thanks for your work!

**Comment by RandallRebello** [comment]
Hi Shane
The MDTools was updated 16 days ago with support for ArcGIS pro 3.0. 
Please download the setup [here](https://github.com/Esri/mdcs-py/blob/master/MDTools_Setup.zip).

Thanks,.

**Comment by Shane98c** [comment]
Thanks!
