### ISSUE TITLE
Manage Tile Cache fails if user tiling scheme is defined

### ISSUE THREAD

**Issue by giugent** [Esri/mdcs-py#110]
Hello,
I'm experiencing a trouble in using the MTC processing code.
The Tile Cache seems to computed correctly (I can load and visualize) even if I get the bad message "Failed".
Looking at the code in the script SolutionLib.py I guess that the reason of the failure is due to two procedures that are not defined:
returnLevelDetails and modifyConfProperties.
Is it so ?
Thanks in advance for your attention
Giuseppe

**Comment by vijaygit02** [comment]
@giugent , Can you confirm if you get the same behavior by directly using the GP tool in Pro. MDCS is just a wrapper around these core GP tools. If there is an issue with the GP tool then that will manifest in MDCS as well.
