### ISSUE TITLE
Tried to use mdtools after installing Pro3.0.0 failed on licensing

### ISSUE THREAD

**Issue by gauteaasolaas** [Esri/mdcs-py#111]
C:\work\orto>"c:\Program Files\ArcGIS\Pro\bin\mdtools.exe" --md=MosaicDataset_ep.gdb\s3047 --embedrasterproxy
. Initializing ArcObjects...
...FAILED to initialize license...(Line: 52)
C:\work\orto>

**Comment by vijaygit02** [comment]
@gauteaasolaas ,
We are working on the fix and will get back to you sooner than later.

Thanks

**Comment by slibby** [comment]
I am also facing this

**Comment by vijaygit02** [comment]
@gauteaasolaas  and @slibby .
Can you check the new setup. The issue should be resolved now.

**Comment by gauteaasolaas** [comment]
Thanks!

**Comment by slibby** [comment]
I downloaded the installer just now, and attempted to install, but received an error:
![image](https://user-images.githubusercontent.com/1691225/210585733-b5824f8a-be68-45dd-bf9a-ebe8fa04e715.png)

**Comment by abhiataero** [comment]
@slibby  the issue is resovled, can you check it out

**Comment by slibby** [comment]
It gets past that issue now, but when I run the install it doesn't seem to actually deploy mdtools.exe to the \bin folder, here is the result I see:
![image](https://user-images.githubusercontent.com/1691225/211242925-aacd4b8b-ae39-4b36-b096-5bd71dde098b.png)
But there are no new files in \bin, and no mdtools.exe. 

Running Pro 3.0.3, ran the EXE both as user and as Administrator - same result.

**Comment by imrankhan-pathan** [comment]
@slibby I've updated the MDTools setup. This should fix your issue. Can you try installing the latest MDTools setup?
