### ISSUE TITLE
How to register Mosaic Datasets Footprint layer for web tool publication

### ISSUE THREAD

**Issue by MoritzMoreira** [Esri/mdcs-py#125]
I am trying to publish a Python script as a web tool, which calls a MDCS (Mosaic Dataset Configuration Script). It flags missing data stores for /Footprints. The .gdb folder is registered as a datastore. The xml config file:

`<?xml version="1.0" encoding="utf-8"?>
<Application>
  <Name>Amberg1Demo</Name>
  <Command>CM+AR</Command>
  <Workspace>
    <WorkspacePath>D:\...\DTK-Workflow-test\Services_test</WorkspacePath>
    <Geodatabase>Amberg</Geodatabase>
    <MosaicDataset>
      <MosaicDatasetType>Source</MosaicDatasetType>
      <Name>Amberg1</Name>
      <SRS>25832</SRS>
      <num_bands>3</num_bands>
      <pixel_type>8_BIT_UNSIGNED</pixel_type>
      <AddRasters>
        <AddRaster>
          <dataset_id>Amberg</dataset_id>
          <raster_type>Raster Dataset</raster_type>
          <Sources>
            <data_path>C:\...\Downloads\Amberg\Amberg</data_path>
          </Sources>
          <filter>*</filter>
        </AddRaster>
      </AddRasters>
    </MosaicDataset>
  </Workspace>
</Application>`

2 Lines of Python to trigger the MDCS (toolbox script):

`import MDCS
MDCS.main(2, ["x", r"-i:C:\...\Downloads\mdcs-py-master\mdcs-py-master\Parameter\Config\Amberg1.xml"])`

It also flags "24046 tool calculate field cannot use VB expressions for services".

Do I have to enter /Footprints somehow as a parameter? Not sure how to, because the mosaic dataset does not exist before running the tool. Also, where would I use the parameters variable?

Or do I have to do something like ", </StageService_server>, <UploadServiceDefinition_server>", in the xml, but for geoprocessing services?

On the other hand, in this video at 23:14 the guy clearly says it's possible. https://mediaspace.esri.com/meia/t/1_q98qok22

Another thing I do not understand is that I successfully published scripts calling MDCS before, although they never executed without errors. To get rid of the errors, I introduced a parameter and canged some path variables. Now, after that,for some reason these flags come up at the at analysis step before publishing.

**Comment by vijaygit02** [comment]
@MoritzMoreira ,

Are you trying to run CV tool? I don't see that command in the config. CV tool will only support Python syntax in ArcPro
Were you able to run the workflow locally first?

Apologies for late reply

**Comment by MoritzMoreira** [comment]
thanks for the reply, but I am not anymore in the organisation with that project, I am trying to do it with QGIS and Lizmap-WPS now...

**Comment by vijaygit02** [comment]
@MoritzMoreira I'll be closing the issue. let us know if you need any help in future
