### ISSUE TITLE
Can we select capabilities while publishing the service?

### ISSUE THREAD

**Issue by aafaque33** [Esri/mdcs-py#34]
Hi I just tried publishing a service using publishing commands and it worked.

I also wanted to select service Capabilities like WCS and WMS selected at time of publishing. tried to look in documentation and online did not find any clue how to pass Capabilities information into service definition or service definition draft.

![publishing](https://cloud.githubusercontent.com/assets/10885595/23716451/fec0e9ec-03f5-11e7-935b-c47fdf8ff01a.PNG)

**Comment by abhiataero** [comment]
@aafaque33  can i close this issue
