### ISSUE TITLE
AWS S3 Bucket to Proxy not referencing

### ISSUE THREAD

**Issue by DouglasBradley** [Esri/mdcs-py#48]
I am trying to publish a mosaic dataset on an EC2 machine (where our ESRI Enterprise and Image Server resides) using raster proxies created with the Optimize raster tool. The source .MRF images have been loaded into an AWS S3 bucket, I have provided the AWS credentials to the EC2 machine using the AWS CLI. The mosaic dataset fails to reference the S3 bucket. I have tried loading the mosaic using a .csv table and altering the source URL to include (\\VSIS3\Http:\\) and it still fails to reference the imagery.  Is there anything obvious that I am missing that will solve this issue?

**Comment by abhiataero** [comment]
@DouglasBradley  check the permission on s3 bucket, if it is a secured bucket the urls should be /vsis3/<bucketname/path

**Comment by DouglasBradley** [comment]
> @DouglasBradley check the permission on s3 bucket, if it is a secured bucket the urls should be /vsis3/<bucketname/path

Thank you, I hadn't given the EC2 machine the correct permissions to access the S3 bucket. Its working great now. Thank you.
