### ISSUE TITLE
Cannot install the tool for ArcGIS Pro 2.5

### ISSUE THREAD

**Issue by vipapril** [Esri/mdcs-py#52]
Hi,

I've just downloaded and unzipped the tool.
When I ran the MDTool_Setup.exe, I only saw the option for ArcMap 10.7 components. However, while I have Pro 2.5 installed, I would like to utilize the tools in Pro.

I further looked up C:\Program Files\ArcGIS\Pro\bin, but I still failed to find the MDTool.

Is the tool support Pro 2.5?

Best,
April

**Comment by abhiataero** [comment]
The setup has been updated t support 2.5 and 2.6
