### ISSUE TITLE
Is there any documentation on how to use data['response']

### ISSUE THREAD

**Issue by anpe00** [Esri/mdcs-py#57]
The file MDCS_UC.py have some examples among which I can find "sample02."

def sample02(self, data):
        log = data['log']           # How to use logging within the user function.
        log.Message('Returning multiple values', 0)
        data['useResponse'] = True
        data['response'] = ['msg0', 'msg1', 'msg2']
        data['status'] = True   # overall function status
        return True    # True must be returned if data['useResponse'] is required. data['response'] can be used to return multiple values.

Is there anyone who knows how to actually the values in data['response']?
Is there any documentation?

I'm building my own custom commands and want to return som values from such a command. Just need to know how to do it. :)

//Anders

**Comment by vijaygit02** [comment]
Hi Anders,

The argument type 'data' is a dictionary which has the few keywords defined in it which are made available at run time to be used in any of your custom function. Have you referred to page 7 in MDCS documentation present under Documentation folder??

if you wish to return multiple values from your custom function , you can return those values instead of "True"

e.g.  return val1,val2

Hope this helps.

Best Regards,
Vijay

**Comment by anpe00** [comment]
Thanks the for the respons Vijay,
I have read the documentation but I still don’t understand. ☹
I have built a custom function that is checking whether or not a mosaic dataset exists. Since I do not understand how to return the answer to my calling bat-file (or powershell script) I have to write the answer to a file and then open that file to get hold of the value.
How can I return the answer in a better way? Is the data['response'] a way of doing it.
Do you have an example?

**Comment by vijaygit02** [comment]
Hi Anders ,

Apologies for the late reply.
If your objective is to somehow return the answer back to the batch file , I can suggest using sys.exit() .
So if the mosaic doesnt exist then you exit out the program with sys.exit(0) error.
This error can then be used using "errorlevel" inside your bat file.
data['response'] would not be ideal in this case.

Hope this helps.

Best Regards,
Vijay

**Comment by abhiataero** [comment]
@anpe00  did the suggestion from @vijaygit02  resolve the issue
