### ISSUE TITLE
Support for OPeNDAP?

### ISSUE THREAD

**Issue by hyoklee** [Esri/mdcs-py#59]
I can see [MakeOPeNDAPRasterLayer](https://pro.arcgis.com/en/pro-app/tool-reference/multidimension/make-opendap-raster-layer.htm). Is there way to create a mosaic dataset using a set of OPeNDAP URLs as raster source via MDCS?

**Comment by abhiataero** [comment]
@hyoklee currently it is not supported 

i am closing this issue as this part of core raster type and not part of MDCS

**Comment by hyoklee** [comment]
@abhiataero That makes sense. Can you ask core raster type team to support OPeNDAP?
