### ISSUE TITLE
Improvement - Setting projection horizontal and vertical by factory code

### ISSUE THREAD

**Issue by chritomix** [Esri/mdcs-py#62]
Currently when creating mosaic, I must use a well-known text string representation  (like "_PROJCS['WGS_1984_Web_Mercator_Auxiliar...."_). But I would love to use Factory code directly (4326) and for both projections (horizontal and vertical)
Here is the possible solution to change script in CreateMD.py
![image](https://user-images.githubusercontent.com/32699393/94426827-767fc180-018e-11eb-904e-8f4227b288f0.png)
and in xml file:
![image](https://user-images.githubusercontent.com/32699393/94427274-189fa980-018f-11eb-9f2f-3e25d84e3c57.png)

**Comment by abhiataero** [comment]
@chritomix  it should work without any change as it is currently supported

**Comment by vijaygit02** [comment]
@chritomix ,

We have incorporated the change in the MDCS code.
Now you should be able to pass the WKID codes using a '/' seperator.

Thanks for your inputs.
