### ISSUE TITLE
Version Check does not time out when not connected to the internet. 

### ISSUE THREAD

**Issue by gbrunner** [Esri/mdcs-py#70]
Not all customers use MDCS from a machine that is connected to the internet. When they aren't connected to the internet the MDCS version checker hangs and slows the process down by 5 or 10 minutes. Remove those lines so that we don't include it.

**Comment by RandallRebello** [comment]
@gbrunner 
Hi, 
The fastest way to skip checking for update would be to delete/rename the checkforupdate .json file. 
For MDCS it can be found here. 
c:\Image_Mgmt_Workflows\MDCS\scripts\CheckForUpdate.json
This would be the most effective way to skip it. 

Once MDCS finds this file missing it will just show a message and continue. It will not try to connect to anything.

**Comment by CodyBenkelman** [comment]
Randall
I’m not sure if replying to this thread is the best place for discussion, but 2 questions

  1.  Is this method for avoiding the version check documented?
  2.  Is there a bug that needs to be fixed?  If the version check doesn’t respond, (I think) it should time out and proceed much faster than 5+ minutes.

Thanks
Cody
