### ISSUE TITLE
logger module

### ISSUE THREAD

**Issue by RandallRebello** [Esri/mdcs-py#76]
Logger Module is not able to print messages with unicode characters in it with python 3.7.10 in ArcGIS Pro 2.8+ 
Affects all workflows using this module.

**Comment by Chamlika** [comment]
The issue is unrelated to Unicode messages. It was an unhandled exception due to invalid user input. 
Code to be updated to catch such exceptions.

**Comment by vijaygit02** [comment]
@Chamlika , is it something @bikesbade  can look into?

**Comment by RandallRebello** [comment]
@vijaygit02 @Chamlika I cant remember what this was about.  Could not find an email chain also. If it comes up again.. Will reopen this issue. One of you can close the issue.
