### ISSUE TITLE
Layer name when calculating a field can cause errors

### ISSUE THREAD

**Issue by ys-bluemarble** [Esri/mdcs-py#88]
The layer name created when calculating a field in [line 934 of solutionsLib.py](https://github.com/Esri/mdcs-py/blob/8ecaf9b5cda5c33537cae4a21809b12894598cba/scripts/solutionsLib.py#L934) can cause an error when there are multiple calculations and they all run quickly.  The name is based on the timestamp to the nearest second.  When two calculations are closer than a second from each other, they can have the same layer name.

Also, the day is used in place of the month in the layer name.  This probably doesn't cause any problems.

Proposed solution: change format of layer name to include milliseconds and also put month in the right place:

`lyrName = 'lyr_%s_%s' % (str(self.m_base.m_last_AT_ObjectID),datetime.strftime(datetime.now(),"%Y%m%d%H%M%S%f"))`

**Comment by Chamlika** [comment]
@vijaygit02 Can you review and integrate the changes from @ys-bluemarble to include into the masters, thanks!
