### ISSUE TITLE
MDCS and optimize rasters

### ISSUE THREAD

**Issue by mapface** [Esri/mdcs-py#98]
I'm using mdcs along with optimize rasters to create and then convert TIF overviews to MRF overviews. Then I want to run mdcs again to then swap the TIF overviews for the MRFs in the mosaic dataset. It works fine except the last step of adding the MRFs - below is the error and I've attached my batch file, screen shot of overviews folder and the remove raster config for mdcs. Any advice?  

```
Adding rasters:
				<Error>
					<type>critical</type>
					<text>No new mosaic dataset items added to dataset (Test_Data). Verify the input data path/raster type is correct</text>
				</Error>
				<Error>
```

[remove_raster_config.txt](https://github.com/Esri/mdcs-py/files/8987847/remove_raster_config.txt)

[example_batch.txt](https://github.com/Esri/mdcs-py/files/8987850/example_batch.txt)

![overview_folder](https://user-images.githubusercontent.com/107257690/175840739-9dc7af49-41c1-46d0-ad83-4775bb9d9c56.PNG)

**Comment by vijaygit02** [comment]
@mapface , in the config file you have the raster type as <raster_type>Raster_Dataset</raster_type> which is incorrect it should be <raster_type>Raster Dataset</raster_type>
