### ISSUE TITLE
Build Overviews - Empty TIFS?

### ISSUE THREAD

**Issue by mapface** [Esri/mdcs-py#99]
Having an additional issue with empty TIFS being created from the BO command, config is attached along with log file - runs without errors  however the TIFs are quite small and nothing draws in ArcGIS Pro. 

[create_md_build_overview.txt](https://github.com/Esri/mdcs-py/files/8987986/create_md_build_overview.txt)
[create_build_overviews_20220627T111706.txt](https://github.com/Esri/mdcs-py/files/8987991/create_build_overviews_20220627T111706.txt)
![tif_overviews](https://user-images.githubusercontent.com/107257690/175843719-7c6d8ea9-9d40-45b5-af69-894e539ea19c.PNG)
 
 When I define and build overviews in ArcPro they come out fine:
 
[arcpro_py_export.txt](https://github.com/Esri/mdcs-py/files/8988017/arcpro_py_export.txt)
![tif_overview_pro](https://user-images.githubusercontent.com/107257690/175844161-7b0cc52d-a533-4963-af24-3cc5eda5c721.PNG)

**Comment by vijaygit02** [comment]
@mapface , this can happen if for some reason the mosaic is not able to access the underlying imagery. Can you confirm if the primary rasters load fine in Pro and if they do can you try running BO through Pro once just to see if the issue persists or not.
MDCS is just a wrapper around the inbuilt GP tools, so most probably if for some reason things don't work out in Pro they will not work out in MDCDs.
Hope this helps.

**Comment by mapface** [comment]
I can confirm the primary rasters load fine in pro, and as I said in my original post running BO in Pro builds them successfully it's just using arcpy results in blank overviews. The primary rasters are MRF proxies with the data in AWS S3.

**Comment by vijaygit02** [comment]
@mapface ,
The above comment first says "just using arcpy results in blank overviews" and then you have attached a script (uses arcpy) through which overviews are getting generated fine?
Are you running this script inside Pro or in outside Pro as a stand alone script.

Vijay

**Comment by vijaygit02** [comment]
@mapface , Since we haven't heard back from you I am closing this issue for now however feel free to reopen it anytime you need further assistance.
